### PR TITLE
Major changes to pulp_win

### PR DESCRIPTION
**Pull request by mibanescu**
I am not proud of failing to group together patches that were logically dealing with the same thing, but I struggled with testing my code, and my deployment involved committing stuff on one machine and building the rpm on another.

There are fundamental differences in the way I modified the plugin:
- I tried to follow the Windows terminology for unit keys and metadata. So instead of name/version, it is now ProductName/ProductVersion
- I want the exported repository to contain a meatada file (I haven't implemented that yet), probably json, listing all available packages in that repo. Much easier than doing traversal over HTTP, and the json file could include all the fields we need. For this to work, I needed to make the repository structure somewhat similar to yum repos: the packages live at a lower level, under a "repos" subdirectory, so metadata and packages don't mix up.

Differences that are not critical:
- python-sh is gone
- msiinfo is run on the server, instead of the client
- the distributor is vastly different, since the Step classes in upstream pulp make things a lot easier

Do you have any plans for the future of the plugin? If so, maybe we can collaborate and design something rather than me coming up with things.

Thank you so much, this was a great starting point for me to learn how pulp plugins work!

### CODE REVIEW

**Comment by lsjostro** [comment]
@mibanescu Thanks for the PR!
Nice to hear that you found it useful! I've not been using this for a while though. I don't really know if there are anyone else except you that use this plugin. 

So if you would be interested in continue maintaining it, that would be super.. Let me know what you think.. 

I'll have a look at the code and get back to you in a couple of days.

Cheers,
Lars

**Comment by mibanescu** [comment]
Thanks! I have a few additions to make this coming week. I am not sure to what extent we're going to use this plugin (or pulp, for that matter), but I want to reach some sort of stability even if we end up not using it.

**Comment by mibanescu** [comment]
Do you happen to have an example of an exe that you were planning to make available via pulp?

I thought "installable" exe files could be queried just like msi files can, but I couldn't get msiinfo to work on one.

**Comment by lsjostro** [comment]
I've haven't found a way to extract info from the .exe unfortunately. I guess it could be done with "wine" or something similar..  and you're right msiinfo only extract msi-pkgs.  I think Nuget packages would be better and easier to support. But that might be separate plugin?

**Comment by mibanescu** [comment]
Separate plugin sounds better, or second phase of this plugin. With that in mind, do you find it reasonable to remove support for .exe in pulp_win?

**Comment by lsjostro** [comment]
you may remove the .exe support.

**Pull request merged**
