### PR TITLE
Port to pulp 2.10

### PR DESCRIPTION
**Pull request by mibanescu**

### CODE REVIEW

**Comment by lsjostro** [comment]
Awesome! LGTM! 👍

**Comment by mibanescu** [comment]
I am in the process of editing https://pulp.plan.io/projects/pulp/wiki/Community_Plugins to "advertise" the plugin. Would you prefer I use your git repo, or should I use mine, given that I pretty much have to maintain it, since we use it in production?

**Comment by lsjostro** [comment]
Good point! You may point it to your repo.  We should also add a note in my repo that the maintainship/upstream have moved.

**Comment by mibanescu** [comment]
Thanks, I have changed that page.

**Pull request merged**
